spring:
  application:
    name: api-gateway
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true
zuul:
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 8000
#  SendErrorFilter:
#    error:
#      disable: true