spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启通过服务中心的自动根据 serviceId 创建路由的功能
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
      prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: debug