spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
        prefer-ip-address: true
feign:
  hystrix:
    enabled: true
