spring:
  application:
    name: provider
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
